#! /bin/bash -e

if (( $# != 2 ))
then

    echo "usage: $0 yaml_file dumpfile"
    exit 99;

else

    VIRTUALENVBINDIR="$HOME/.virtualenvs/budgetbot/bin";
    DBNAME=`$VIRTUALENVBINDIR/budgetbot-config $1 database_name`
    DBUSER=`$VIRTUALENVBINDIR/budgetbot-config $1 database_user`

    sudo -u postgres dropdb --if-exists $DBNAME
    sudo -u postgres createdb --owner $DBUSER $DBNAME

    # sudo -u postgres createlang plpythonu $DBNAME
    # sudo -u postgres psql -v "ON_ERROR_STOP=1" --quiet -d $DBNAME -c 'create extension "hstore";'
    # sudo -u postgres psql -v "ON_ERROR_STOP=1" --quiet -d $DBNAME -c 'create extension "uuid-ossp";'
    # sudo -u postgres psql -v "ON_ERROR_STOP=1" --quiet -d $DBNAME -c 'create extension "pgcrypto";'
    # sudo -u postgres psql -v "ON_ERROR_STOP=1" --quiet -d $DBNAME -c 'create extension "citext";'
    # sudo -u postgres psql -v "ON_ERROR_STOP=1" --quiet -d $DBNAME -c "create extension btree_gist;"

    sudo -u postgres pg_restore --no-owner --exit-on-error -U $DBUSER -d $DBNAME $2

    echo "Now run budgetbot-upgrade-database $1"

fi
