#! /bin/bash

exec gunicorn \
--workers 1 \
--timeout 600 \
--bind 127.0.1.1:6661 \
--pid /tmp/budgetbot.pid \
budgetbot.configwrapper:ConfigWrapper.from_yaml_file_name\(\"dev.yaml\"\).build_webapp\(\)
