#! /bin/bash

exec /home/budgetbot/.virtualenvs/budgetbot/bin/gunicorn \
--workers 2 \
--timeout 600 \
--bind 127.0.0.1:6663 \
--pid /tmp/budgetbot.pid \
budgetbot.configwrapper:ConfigWrapper.from_yaml_file_name\(\"prod.yaml\"\).build_webapp\(\)
